name: Python CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest

    - name: Run pylint
      run: |
        pylint calc.py test_calculator.py

    - name: Run tests with pytest
      run: |
        pytest test_calculator.py
